config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  root to: "home#index"
  get "home/index"

  resources :employee_checks, only: [:create]
end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/company_branch.rb
# == Schema Information
#
# Table name: company_branches
#
#  id         :bigint           not null, primary key
#  name       :string
#  address    :string
#  created_at :datetime         not null
#  updated_at :datetime         not null
#
class CompanyBranch < ApplicationRecord
  has_many :employees

  validates :name, presence: true, uniqueness: true
end

app/models/employee.rb
# frozen_string_literal: true

# == Schema Information
#
# Table name: employees
#
#  id                :bigint           not null, primary key
#  email             :string
#  name              :string
#  position          :string
#  employee_number   :integer
#  status            :boolean          default(TRUE)
#  company_branch_id :bigint           not null
#  private_number    :string
#  created_at        :datetime         not null
#  updated_at        :datetime         not null
#
class Employee < ApplicationRecord
  belongs_to :company_branch
  has_many :employee_checks

  validates :email, :employee_number, :private_number, presence: true, uniqueness: true
  validates :company_branch, presence: true

  # override destroy action
  def destroy
    update(status: (status ? false : true))
  end

  def self.absences_month(year = Date.today.year, month = Date.today.month)
    employees = []
    date_init = "#{year}-#{month}-01".to_date
    (date_init.beginning_of_month..date_init.end_of_month).to_a.each do |day|
      employees += absences(day)
    end
    employees
  end

  def self.absences(day)
    return [] unless day <= Time.now.utc.to_date

    select('employees.*', "'#{day}' as day")
      .joins("LEFT JOIN employee_checks ON employees.id = employee_checks.employee_id AND
      Date(employee_checks.created_at AT TIME ZONE 'UTC' AT TIME ZONE '#{Time.now.in_time_zone.strftime("%Z")}') = '#{day}'")
      .having('COUNT(employee_checks.id) = ?', 0).group('employees.id')
  end

  def self.attendances(day)
    select('employees.*', "'#{day}' as day", 'employee_checks.created_at as time', 'employee_checks.check_type')
      .joins("LEFT JOIN employee_checks ON employees.id = employee_checks.employee_id AND
        Date(employee_checks.created_at AT TIME ZONE 'UTC' AT TIME ZONE '#{Time.now.in_time_zone.strftime("%Z")}') = '#{day}'")
      .having('COUNT(employee_checks.id) > ?', 0).group('employee_checks.id, employees.id')
      .order('employee_checks.created_at')
  end

  def absence?(day)
    return false unless day <= Date.today

    true unless EmployeeCheck.where(employee_id: id, created_at: day.midnight..day.end_of_day).count.positive?
  end
end

app/models/employee_check.rb
# frozen_string_literal: true

class EmployeeCheck < ApplicationRecord
  belongs_to :employee, optional: true
  attr_accessor :private_number

  enum check_type: %i[check_in check_out]

  validates :private_number, presence: true
  validate :employee_existence
  before_create :fill_info

  private

  def employee_existence
    return if Employee.find_by(private_number: private_number)

    errors.add 'employee', "private number #{private_number} not found."
  end

  def fill_info
    self.employee = Employee.find_by(private_number: private_number)
    self.check_type = decide_type
  end

  def decide_type
    last_employee_check = employee.employee_checks.last
    return :check_in unless last_employee_check

    last_employee_check.check_type == 'check_in' ? :check_out : :check_in
  end
end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id                     :bigint           not null, primary key
#  username               :string
#  email                  :string           default(""), not null
#  encrypted_password     :string           default(""), not null
#  reset_password_token   :string
#  reset_password_sent_at :datetime
#  remember_created_at    :datetime
#  created_at             :datetime         not null
#  updated_at             :datetime         not null
#
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/employee_checks_controller.rb
class EmployeeChecksController < ApplicationController
  def create
    @employee_check = EmployeeCheck.new(employee_check_params)

    respond_to do |format|
      if @employee_check.save
        format.html do
          redirect_to root_path,
                      notice: "#{@employee_check.check_type} stored correctly for #{@employee_check.employee.name} at #{@employee_check.created_at}."
        end
        format.json { head :no_content }
      else
        format.html { render '/home/index', status: :unprocessable_entity }
        format.json { render json: @employee_check.errors, status: :unprocessable_entity }
        format.js   { render 'employee_checks/form_errors', locals: { errors: @employee_check.errors } }
      end
    end
  end

  private

  def employee_check_params
    params.require(:employee_check).permit(:check_type, :employee, :private_number)
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @employee_check = EmployeeCheck.new
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/employee_checks/form_errors.js.erb
existing = document.getElementById('error_explanation');
if (existing) { document.getElementById('error_explanation').remove() };
html_errors = document.createElement('div');
html_errors.setAttribute('id', 'error_explanation');
html_errors.setAttribute('class', 'alert alert-danger alert-dismissible fade show');
html_errors.setAttribute('role', 'alert');
html_errors.innerHTML = '<h4><%= pluralize(errors.count, "error") %></h4>'+
  '<ul>'+
    <% errors.each do |error| %>
      '<li><p><%= error.full_message %></p></li>'+
    <% end %>
  '</ul>'+
  '<button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>';
document.querySelector('form').prepend(html_errors);

app/views/home/index.html.erb
<div class="cover-container d-flex w-100 h-100 p-3 mx-auto flex-column">
	<%= render 'partials/navbar' %>
  <main class="px-3">
    <div class="container col-xl-10 col-xxl-8 px-4 py-5">
      <div class="row align-items-center g-5 py-5">
        <div class="col-lg-7 text-center text-lg-start">
          <h1 class="display-4 fw-bold lh-1 mb-3">Access to employees</h1>
          <p class="col-lg-10 fs-4">Enter your private employee number to be able to mark your entry and exit from the store.</p>
        </div>

        <div class="col-10 mx-auto col-lg-5">
          <%= render 'partials/notification' %>
          <%= form_with( model: @employee_check, local: false, class:"p-5 border rounded-3 bg-light" ) do |form| %>
            <div class="form-floating mb-3">
              <%= form.text_field :private_number, class:"form-control" %>
              <%= form.label :private_number %>
            </div>
            <%= form.submit "Check", class:"w-100 btn btn-lg btn-primary" %>
            <hr class="my-4">
            <small class="text-muted">If you do not remember your number it is on the back of your card.</small>
          <% end %>
        </div>
      </div>
    </div>
  </main>
  <%= render 'partials/footer' %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Kata07RejojChecadorEquipo04K07</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body class="d-flex h-100 text-center">
    <%= yield %>
  </body>
</html>

app/views/partials/_footer.html.erb
<footer class="footer mt-auto py-3 bg-light fixed-bottom">
  <div class="container">
    <p>Exercise <a href="https://github.com/BC-MAR-21-ROR/kata-07-rejoj-checador-equipo-04-k07" class="">Kata 07 Reloj checador</a>, for <a href="http://www.brightcoders.com/" class="">BrightCoders</a>.</p>
  </div>
</footer>

app/views/partials/_navbar.html.erb
<header class="mb-auto">
  <div>
    <h3 class="float-md-start mb-0">
      <%= link_to "Kata 07 Reloj Checador", root_path, class: "link-dark" %>
    </h3>
    <nav class="nav nav-masthead justify-content-center float-md-end">
      <%= link_to "Admin access", new_admin_user_session_path, class: "nav-link" %>
    </nav>
  </div>
</header>

app/views/partials/_notification.html.erb
<% if flash[:notice] %>
<div class="alert alert-success alert-dismissible fade show" role="alert">
  <strong><%= notice %></strong>
  <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
</div>
<% end %>

<% if flash[:alert] %>
<div class="alert alert-danger alert-dismissible fade show" role="alert">
  <strong><%= alert %></strong>
  <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
</div>
<% end %>